name: CI

on: [push]

jobs:
  build1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world in build1!
    - name: Run a multi-line script
      run: |
        sleep 15 && date +"%Y/%m/%d %p %I:%M:%S"
        echo Add other actions to build,
        echo test, and deploy your project.

  build2:
    needs: [build1]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world in build2!
    - name: Run a multi-line script
      run: |
        sleep 10 && date +"%Y/%m/%d %p %I:%M:%S"
        echo Add other actions to build,
        echo test, and deploy your project.

  build3:
    needs: [build1,build2]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world in build3!
    - name: Run a multi-line script
      run: |
        sleep 0 && date +"%Y/%m/%d %p %I:%M:%S"
        echo Add other actions to build,
        echo test, and deploy your project.
